- name: Install vscode
  apt:
    name: code
  become: yes

- name: Install dbeaver
  apt:
    deb: http://dbeaver.jkiss.org/files/dbeaver-ce_latest_amd64.deb
  become: true

- name: Install aws-cli
  snap:
    name: aws-cli
    state: present
    classic: true
  become: yes

- name: Install insomnia
  snap:
    name: insomnia
    state: present
  become: yes

- name: Install zsh
  shell: |
    if [ ! -f ~/.zshrc ]; then
      curl https://raw.githubusercontent.com/viasite-ansible/ansible-role-zsh/master/install.sh | bash
    fi;
  become: yes